apiVersion: v1
kind: Service
metadata:
    name: "xerytelegram001-5314"
    labels:
        app: "xerytelegram001-5314"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "xerytelegram001-5314"